version: "3.5"

services:
  web_head:
    hostname: header
    build: .
    restart: always
    networks:
      - challenge
    ports:
      - 10780:80


networks:
  challenge:
    external:
      name: challenge
