version: "3.5"

services:

  db:
    hostname: sqli
    build: ./mysql
    #command: --default-authentication-plugin=mysqlnative_password
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: sqli
      MYSQL_PASSWORD: sqli
    networks:
      - sqli_db

  php:
    hostname: php
    build: ./php
    restart: always
    volumes:
      - /var/www/html:/var/www/html/
    depends_on:
      - db
    networks:
      - challenge
      - sqli_db


networks:

  challenge:
    external:
      name: challenge

  sqli_db:
    name: sqli_db
    internal: true