version: "3.5"

services:

  sqli_db:
    hostname: sqli
    build: ./mysql
    #command: --default-authentication-plugin=mysqlnative_password
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: sqli
      MYSQL_PASSWORD: sqli
    volumes:
      - ./mysql/cnf/:/etc/mysql/conf.d/
    networks:
      - sqli_nw

  php:
    hostname: php
    build: ./php
    restart: always
    volumes:
      - /var/www/html:/var/www/html/
    depends_on:
      - sqli_db
    networks:
      - challenge
      - sqli_nw


networks:

  challenge:
    external:
      name: challenge

  sqli_nw:
    name: sqli_nw
    internal: true